# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache NPM
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Cache Elm
      uses: actions/cache@v3
      id: elm-cache
      with:
        path: ~/.elm
        key: ${{ runner.os }}-elm-${{ hashFiles('**/elm.json') }}
        restore-keys: |
          ${{ runner.os }}-elm-
    - name: Download dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test
      env:
        CI: true
    - name: Publish Elm (as needed)
      uses: dillonkearns/elm-publish-action@1.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-elm: ./node_modules/.bin/elm
    - name: Publish (as needed)
      uses: JS-DevTools/npm-publish@v1
      if: env.NPM_TOKEN != 0
      with:
        token: ${{ env.NPM_TOKEN }}
