name: Sonatype Lifecycle Evaluation

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
env:
  SonatypeUrl: "https://finos.sonatype.app/platform/"
  SonatypeAppId: "morphir-elm"
  SonatypeScanTarget: "."
  ExcludeDirectory: "**/docs/ **/.*'"
    
jobs:
  scan:
    name: Build
    runs-on: ubuntu
    steps:
      - name: Sonatype Lifecycle SCA Scan
        # if: github.repository_owner == 'finos'
        id: evaluate
        if: github.event_name == 'pull_request_target'
        uses: sonatype/actions/evaluate@v1
        with:
          iq-server-url: ${{ env.SonatypeUrl }}
          username: ${{ secrets.SONATYPE_SCANNER_USERNAME }}
          password: ${{ secrets.SONATYPE_SCANNER_PASSWORD }}
          application-id: ${{ env.SonatypeAppId }}
          stage: "build"
          scan-targets: ${{ env.SonatypeScanTarget }}
          module-exclude: ${{ env.ExcludeDirectory }}
      
      - name: Save Sonatype SBOM
        uses: sonatype/actions/fetch-sbom@v1
        if: steps.evaluate.outputs.scan-id
        with:
          iq-server-url: ${{ env.SonatypeUrl }}
          username: ${{ secrets.SONATYPE_SCANNER_USERNAME }}
          password: ${{ secrets.SONATYPE_SCANNER_PASSWORD }}
          application-id: ${{ env.SonatypeAppId }}
          scan-id: ${{ steps.evaluate.outputs.scan-id }}
          sbom-standard: spdx
          sbom-version: 2.3
          artifact-name: ${{ env.SonatypeAppId }}-bom
